'use server';

/**
 * @fileOverview This file defines a Genkit flow to recommend the best mathematical model for financial forecasting based on historical data and real-world results.
 *
 * - getModelRecommendation - A function that processes historical financial data and provides a recommendation for the best-suited forecasting model.
 * - GetModelRecommendationInput - The input type for the getModelRecommendation function.
 * - GetModelRecommendationOutput - The return type for the getModelRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetModelRecommendationInputSchema = z.object({
  historicalData: z.string().describe('Historical financial data, including income, expenses, and asset values over time.'),
  forecastData: z.string().describe('Forecasted financial data generated by different mathematical models.'),
  realityData: z.string().describe('Real-world financial data observed over the same period as the forecast data.'),
  language: z.enum(['german', 'english']).describe('The language for the generated recommendation.'),
});
export type GetModelRecommendationInput = z.infer<typeof GetModelRecommendationInputSchema>;

const GetModelRecommendationOutputSchema = z.object({
  recommendedModel: z.string().describe('The name of the recommended mathematical model for financial forecasting.'),
  reasoning: z.string().describe('Explanation of why the model was recommended, based on its performance compared to reality data.'),
});
export type GetModelRecommendationOutput = z.infer<typeof GetModelRecommendationOutputSchema>;

export async function getModelRecommendation(input: GetModelRecommendationInput): Promise<GetModelRecommendationOutput> {
  return getModelRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getModelRecommendationPrompt',
  input: {schema: GetModelRecommendationInputSchema},
  output: {schema: GetModelRecommendationOutputSchema},
  prompt: `You are an AI assistant that analyzes financial data to recommend the best mathematical model for forecasting. Your response must be in {{language}}.

  You are provided with historical financial data, forecasted data from different models, and real-world financial data.

  Your goal is to identify the model that most accurately predicts future financial outcomes based on its alignment with the real-world data.

  Historical Data: {{{historicalData}}}
  Forecast Data: {{{forecastData}}}
  Reality Data: {{{realityData}}}

  Based on this information, which model is most accurate and why?
  What are the strengths and weaknesses of the recommended model based on this information?
  Please return a 'recommendedModel' and 'reasoning' for the recommendation.
  `,
});

const getModelRecommendationFlow = ai.defineFlow(
  {
    name: 'getModelRecommendationFlow',
    inputSchema: GetModelRecommendationInputSchema,
    outputSchema: GetModelRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
